---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: branch-planner-iac
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/jozemario/gitops
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: branch-planner-iac
  namespace: flux-system
spec:
  approvePlan: auto
  path: ./tf-planner
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: branch-planner-iac
    namespace: flux-system
