---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helloworld-tf
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/jozemario/gitops
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helloworld-tf
  namespace: flux-system
spec:
  path: ./terraform
  approvePlan: auto
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
    namespace: flux-system
