---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helloworld-tf
spec:
  interval: 1m
  url: https://github.com/jozemario/gitops
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
spec:
  path: ./terraform
  approvePlan: "auto"
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
  writeOutputsToSecret:
    name: helloworld-outputs
