apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: develop
spec:
  interval: 30s
  url: https://github.com/jozemario/gitops
  ref:
    branch: develop
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: develop
spec:
  interval: 1m
  approvePlan: auto
  path: ./tf-staging
  sourceRef:
    kind: GitRepository
    name: develop
