apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-pvc
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
