# apiVersion: traefik.containo.us/v1alpha1
# kind: TLSStore
# metadata:
#   name: default
#   namespace: kube-system
# spec:
#   defaultCertificate:
#     secretName: wildcard-mghcloud-com-xbjjn

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: traefik-config
#   labels:
#     name: traefik-config
#   namespace: kube-system
# data:
#   traefik-config.yaml: |
#     # https://doc.traefik.io/traefik/https/tls/
#     tls:
#       stores:
#         default:
#           defaultCertificate:
#             certFile: '/certs/tls.crt'
#             keyFile: '/certs/tls.key'
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      # - "--providers.file.filename=/config/traefik-config.yaml"
    ports:
      traefik:
        expose: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    # additionalArguments:
    # volumes:
    #   - name: wildcard-mghcloud-com-xbjjn
    #     mountPath: '/certs'
    #     type: secret
    #   - name: traefik-config
    #     mountPath: '/config'
    #     type: configMap
