apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      # - "--certificatesresolvers.myresolver.acme.email=josezero1@gmail.com"
      # - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
    ports:
      traefik:
        expose: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true

    # entryPoints:
    #   web:
    #     address: ":80"

    #   websecure:
    #     address: ":443"

    # certificatesResolvers:
    #   myresolver:
    #     acme:
    #       email: josezero1@gmail.com
    #       storage: acme.json
    #       httpChallenge:
    #         entryPoint: web
