apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-mghcloud-com
  namespace: kube-system
spec:
  secretName: wildcard-mghcloud-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.mghcloud.com"
