apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tofu-controller-planner
    app.kubernetes.io/instance: tofu-controller
  name: branch-planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tofu-controller-planner
      app.kubernetes.io/instance: tofu-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tofu-controller-planner
        app.kubernetes.io/instance: tofu-controller
    spec:
      containers:
        - args: []
          # Update the env variables according to your new deployment
          image: "ghcr.io/flux-iac/branch-planner:v0.15.0-rc.5"
          imagePullPolicy: IfNotPresent
          name: tofu-controller
          ports:
            - containerPort: 8080
              name: http-prom
            - containerPort: 9440
              name: healthz
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 64Mi
      securityContext:
        fsGroup: 1337
      serviceAccountName: tf-controller
      terminationGracePeriodSeconds: 10
