---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: production
spec:
  interval: 1m
  url: https://github.com/jozemario/gitops
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: production
spec:
  interval: 1m
  path: ./tf-production
  approvePlan: "auto"
  sourceRef:
    kind: GitRepository
    name: production
  writeOutputsToSecret:
    name: production-outputs
